### ISSUE TITLE
The process of making and loading datasets

### ISSUE THREAD

**Issue by tzayuan** [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch#3]
Hi,

I'm sorry to bother you. I want to run this architecture on my own datasets, but I ran into some difficulties. Prior to this, I had read the issue and code, but could not solve the problem independently, so I would like to ask the following questions:

- What structure does ".pkl" use to encapsulate datasets?

- Further, how to wrap the "nii/niI.gz" file into the above ".pkl" according to the desired structure? I have the preprocessed datasets of LPBA40(".niI.gz" format, a total of 40 MRI images and their corresponding Ground truth), but I do not know how to load these data into correct "pkl" format files. I tried to find the relevant information, but did not understand and implement it. I hope to get your instructions, thank you!

![image](https://user-images.githubusercontent.com/25738822/126861616-ec2743c4-bb1f-4d99-a734-4f7b73dea09f.png)
![image](https://user-images.githubusercontent.com/25738822/126861631-69147585-5239-4c77-ac7c-3375cbe130a1.png)

In view of these two questions, I made the following reflections combined with issues opened by others, but failed to solve these two problems independently, I will describe my ideas so that you can quickly clarify my questions, My partial understanding and guess are as follows:
    

- For data encapsulation of medical images, a pre-processed MRI image and its corresponding segmentation result (label/ground truth) are encapsulated into an independent "\*\*\*.pkl" file for data reading. PKL = pkload("\*\*\*.pkl"); "data = pkload("\*\*\*.pkl")"; Where 2 means 1(preprocessed MRI image)+1(segmentation result, i.e., ground truth), that is, data[0] is preprocessed MRI image and data[1] is its corresponding ground truth;
But according to the code of datasets.py, this does not seem to be the case, because in "class JHUBrainDataset(Dataset)" getitem is "x, y = pkload(path)", In "class JHUBrainInferDataset(Dataset)", the getitem mode is "x, y, x_seg, y_seg = pkload(path)", It looks like a "***.pkl" file containing two MRI images and their corresponding two ground truths.
    

- According to the code part of reading the dataset in the training stage and validation stage of "datasets.py", I speculated as follows: In the training stage, only preprocessed MRI images were used, without ground truth, because there are no "x_seg" and "y_seg" in "\_\_getitem\_\_" of "class JHUBrainDataset" ; In the validation stage, pre-processed MRI images and their corresponding segmentation results (label/ground truth) were used at the same time.

![image](https://user-images.githubusercontent.com/25738822/126861651-2b31736b-a0ac-4cf4-b59b-3c9c0f5e53ba.png)
![image](https://user-images.githubusercontent.com/25738822/126861669-f8c4ee9a-8238-416d-8a2a-57333a45ee54.png)
![image](https://user-images.githubusercontent.com/25738822/126861709-36a1be69-c559-4d47-9c9b-01d575375f43.png)
![image](https://user-images.githubusercontent.com/25738822/126861688-f617d2c9-ec0c-459a-bb06-f89efe9fad6c.png)

Thanks

**Comment by junyuchen245** [comment]
Hi @tzayuan,

I believe .pkl is a binary file similar to a .npz file (if you are familiar with this). It has a faster reading and writing speed than NIfTI files. The following code is what I used for reading and writing NumPy arrays:
```python
def pkload(fname):
    with open(fname, 'rb') as f:
        return pickle.load(f)
def savepkl(data, path):
    with open(path, 'wb') as f:
        pickle.dump(data, f)

savepkl(data=(moving, fixed), path="images.pkl")
moving, fixed = pkload("images.pkl")
```

Instead of loading four files (i.e., moving image, fixed image, and corresponding label maps), it is desired to load only the moving image and the fixed image during training. This is because loading two files is faster; besides, the training does not involve label maps. For this reason, during the preprocessing step, I saved the images into two directories: one contains images only, and another one contains both images and label maps.
```python
path_1 = "images_only/image_1.pkl"
path_2 = "images_labelmaps/image_1.pkl"
savepkl(data=(moving, fixed), path=path_1)
savepkl(data=(moving, fixed, moving_seg, fixed_seg), path=path_2)
```
Then, I randomly sampled .pkl files for training, validation, and testing according to a ratio of 7:1:2. Note that the files were drawn from ```path_1``` for training, and for validation and testing, the files were drawn from ```path_2```:
```python
root_dir = './'
all_imgs_dir = root_dir + 'images_only/'
all_segs_dir = root_dir + 'images_labelmaps/'
train_dir = root_dir + 'Train/'
val_dir = root_dir + 'Val/'
test_dir = root_dir + 'Test/'
files = glob.glob(root_dir+'images_only/*.pkl')
files_segs = glob.glob(root_dir+'images_labelmaps/*.pkl')
#7:1:2 for training, validation, and testing
num_train = len(files)-math.ceil(len(files)*0.1)-math.ceil(len(files)*0.2)
num_val = math.ceil(len(files)*0.1)
num_test = math.ceil(len(files)*0.2)
print('total number of files: {}, train: {}, val: {}, test: {}'.format(len(files), num_train, num_val, num_test))

idx = 0
random.seed(0)
random.shuffle(files)
random.seed(0)
random.shuffle(files_segs)

for file in files:
    print(file)
    if idx < num_train:
        copy(file, train_dir)
    elif idx >= num_train and idx < num_train + num_val:
        copy(files_segs[idx], val_dir)
    else:
        copy(files_segs[idx], test_dir)
    idx += 1
print(len(glob.glob(train_dir+'*.pkl')))
print(len(glob.glob(val_dir + '*.pkl')))
print(len(glob.glob(test_dir + '*.pkl')))
```

This gives you a basic idea of what I did. You do not need to follow the exact steps. If you would like to use NifTI files, you could do that by simply replacing the ```pkload()``` function with your own ```.nii.gz``` reading function.

I hope this helps.

Thanks,
Junyu

**Comment by tzayuan** [comment]
Hi,

As you said, because the `.PKL` format has higher data loading speed, I also adopted the `.PKL` format data. I have made my dataset into `.PKL` format and loaded it into the model according to your instructions. Since the progress is not fast, I am not sure whether I will encounter other detailed problems of model training (especially to achieve relatively good accuracy). But now this problem has been solved. I can only give you the feedback of this issue first. In addition, I noticed that using '\<code here\>' as part of  markdown gives better readability.

This helps a lot!

Thanks!

**Comment by zhixiaoqiang-haha** [comment]
Hello
       I would like to ask. I converted my brain data set to pkl format, and did not change your parameters. After training, I found that his dice coefficient just reached 0.52 after training, and the resolution of the obtained image is compared. Low. Would you like to ask you about the problem of the transformer network? And during my training process, the indicator curve trend of his validation set is not the same as yours in the paper.
![image](https://user-images.githubusercontent.com/72558526/128832038-9635c4c0-2814-4727-8385-361c72835075.png)

**Comment by junyuchen245** [comment]
Hi @zhixiaoqiang-haha,

This doesn't seem to be correct. If the MSE loss is decreasing, you should see some improvement in the validation dice score. What is your dice score calculated for? For grey matter, white matter or lesion? And how did you preprocess the brain images? Did you use FreeSurfer for preprocessing?

Can you show me the images (and possibly, the labels) before and after the registration?

Junyu

**Comment by zhixiaoqiang-haha** [comment]
Hello&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; Thank you for replying to my message. I did encounter some problems with this algorithm. I would be very grateful if I can get your advice. I use the LPBA40 data set. Below are my fixed image, moving image and configuration. The warped image after the standard, the last one is a label image from my data set.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch] The process of making and loading datasets (#3)





 
Hi @zhixiaoqiang-haha,
 
This doesn't seem to be correct. If the MSE loss is decreasing, you should see some improvement in the validation dice score. What is your dice score calculated for? For grey matter, white matter or lesion? And how did you preprocess the brain images? Did you use FreeSurfer for preprocessing?
 
Can you show me the images (and possibly, the labels) before and after the registration?
 
Junyu
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junyuchen245** [comment]
@zhixiaoqiang-haha I'll take a look at the dataset and let you know. 

Btw, I cannot find the images you mentioned.

**Comment by zhixiaoqiang-haha** [comment]
Hello, I’m sorry, it may be the problem of sending. I tried to send it to you with a large attachment. However, due to the large 3d data set, it cannot be sent successfully. The data set I used is the open source LPBA40.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch] The process of making and loading datasets (#3)





 
@zhixiaoqiang-haha I'll take a look at the dataset and let you know.
 
Btw, I cannot find the images you mentioned.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.


从QQ邮箱发来的超大附件

1eac4fb2a01507d78b2f2283cfa245f.png (89.9K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6d336165edfa9dcaeebb29354062511a0d0a595305060103180b5950574f570c01554c040255071801030056575a5357050a5104664163045052025100005154050254555106540d57010757545a50565352535153044d455b546158&t=exs_ftn_download&code=53aefbc5




5e6e5c7f10c028d85d87d612849612c.png (91.6K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6d63356504a29fc6eeeb7d3545335316050600560205595b1807515c561e555d56501804510557140c5a01570751570f530553556310610c5055505000040708050005575b57590c515b020155025301015a035451504f495b043558&t=exs_ftn_download&code=5c5ec3a9




5f370d7490b8d2a0fcebb1fd3a859c5.png (85.2K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6d3133326bcfcdcfeeb97b621464011f50020a56020207551802500a0249070256001e0b5407001d0257060b510656530402010032473305530204025653070905530b560005035656545150030257035409060b51511d405b56330f&t=exs_ftn_download&code=51322d30




c546d55b7f8410f8cff4ac08490f21a.png (27.6K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6a396534f3a69999e9b12d6415375449515b0155500402031f5a510d521a5255045c48560454544b0400520c0a5607045701530c33146605070d5350060204515401510503515e05545f515550075e520b090306025648165c5e6509&t=exs_ftn_download&code=29e437ff

**Comment by junyuchen245** [comment]
Hi @zhixiaoqiang-haha, 

The images you shared seem to be okay.

I see that you mentioned you did not change anything in my script, by that, do you mean you used the same training script as mine? If so, the problem might lie in the dice score calculation. You can see from https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/utils.py#L163, I hard coded the labels I got from FreeSurfer into 46 labels:
```python
import re
def process_label():
    #process labeling information for FreeSurfer
    seg_table = [0, 2, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 24, 26,
                          28, 30, 31, 41, 42, 43, 44, 46, 47, 49, 50, 51, 52, 53, 54, 58, 60, 62,
                          63, 72, 77, 80, 85, 251, 252, 253, 254, 255]


    file1 = open('label_info.txt', 'r')
    Lines = file1.readlines()
    dict = {}
    seg_i = 0
    seg_look_up = []
    for seg_label in seg_table:
        for line in Lines:
            line = re.sub(' +', ' ',line).split(' ')
            try:
                int(line[0])
            except:
                continue
            if int(line[0]) == seg_label:
                seg_look_up.append([seg_i, int(line[0]), line[1]])
                dict[seg_i] = line[1]
        seg_i += 1
    return dict
```

Therefore, if the dataset you used was not preprocessed using FreeSurfer, then depending on how many labels you got, you should modify the code for dice calculation (e.g., num_classes, etc.) in https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/utils.py#L193:
```python
def dice_val_substruct(y_pred, y_true, std_idx):
    with torch.no_grad():
        y_pred = nn.functional.one_hot(y_pred, num_classes=46)
        y_pred = torch.squeeze(y_pred, 1)
        y_pred = y_pred.permute(0, 4, 1, 2, 3).contiguous()
        y_true = nn.functional.one_hot(y_true, num_classes=46)
        y_true = torch.squeeze(y_true, 1)
        y_true = y_true.permute(0, 4, 1, 2, 3).contiguous()
    y_pred = y_pred.detach().cpu().numpy()
    y_true = y_true.detach().cpu().numpy()

    line = 'p_{}'.format(std_idx)
    for i in range(46):
        pred_clus = y_pred[0, i, ...]
        true_clus = y_true[0, i, ...]
        intersection = pred_clus * true_clus
        intersection = intersection.sum()
        union = pred_clus.sum() + true_clus.sum()
        dsc = (2.*intersection) / (union + 1e-5)
        line = line+','+str(dsc)
    return line
```

**Comment by zhixiaoqiang-haha** [comment]
Hello&nbsp;
&nbsp; &nbsp; &nbsp; Thank you for your help. I have changed your original code before for the problem you have raised. The num_classes of your original dice coefficient are based on the num_classes provided in LPBA40 ([0, 21, 22, 23, 24, 25, 26 , 27, 28, 29, 30, 31, 32, 33, 34, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 61, 62,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 63, 64, 65, 66, 67, 68, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 101, 102, 121, 122, 161, 162,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 163, 164, 165, 166] is assigned a value of 55, which includes a background of 0. But the result of training still does not have the effect of your training.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 上午6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch] The process of making and loading datasets (#3)





 
Hi @zhixiaoqiang-haha,
 
The images you shared seem to be okay.
 
I see that you mentioned you did not change anything in my script, by that, do you mean you used the same training script as mine? If so, the problem might lie in the dice score calculation. You can see from https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/utils.py#L163, I hard coded the labels I got from FreeSurfer into 46 labels:
 import re def process_label():     #process labeling information for FreeSurfer     seg_table = [0, 2, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 24, 26,                           28, 30, 31, 41, 42, 43, 44, 46, 47, 49, 50, 51, 52, 53, 54, 58, 60, 62,                           63, 72, 77, 80, 85, 251, 252, 253, 254, 255]     file1 = open('label_info.txt', 'r')     Lines = file1.readlines()     dict = {}     seg_i = 0     seg_look_up = []     for seg_label in seg_table:         for line in Lines:             line = re.sub(' +', ' ',line).split(' ')             try:                 int(line[0])             except:                 continue             if int(line[0]) == seg_label:                 seg_look_up.append([seg_i, int(line[0]), line[1]])                 dict[seg_i] = line[1]         seg_i += 1     return dict
 
Therefore, if the dataset you used was not preprocessed using FreeSurfer, then depending on how many labels you got, you should modify the code for dice calculation (e.g., num_classes, etc.) in https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/utils.py#L193:
 def dice_val_substruct(y_pred, y_true, std_idx):     with torch.no_grad():         y_pred = nn.functional.one_hot(y_pred, num_classes=46)         y_pred = torch.squeeze(y_pred, 1)         y_pred = y_pred.permute(0, 4, 1, 2, 3).contiguous()         y_true = nn.functional.one_hot(y_true, num_classes=46)         y_true = torch.squeeze(y_true, 1)         y_true = y_true.permute(0, 4, 1, 2, 3).contiguous()     y_pred = y_pred.detach().cpu().numpy()     y_true = y_true.detach().cpu().numpy()     line = 'p_{}'.format(std_idx)     for i in range(46):         pred_clus = y_pred[0, i, ...]         true_clus = y_true[0, i, ...]         intersection = pred_clus * true_clus         intersection = intersection.sum()         union = pred_clus.sum() + true_clus.sum()         dsc = (2.*intersection) / (union + 1e-5)         line = line+','+str(dsc)     return line
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhixiaoqiang-haha** [comment]
Hello
&nbsp; &nbsp; &nbsp; &nbsp;Sorry to trouble you again. I found a problem. After I finished the training, I found that my fixed image, moving image and warped image were saved through the infer.py test. I found that the registered warped image has a higher pixel resolution. Low, and some information is certain. Could this be the reason why my DICE coefficient cannot reach a better value? I wonder if you encountered this problem during training?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 上午6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch] The process of making and loading datasets (#3)





 
Hi @zhixiaoqiang-haha,
 
The images you shared seem to be okay.
 
I see that you mentioned you did not change anything in my script, by that, do you mean you used the same training script as mine? If so, the problem might lie in the dice score calculation. You can see from https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/utils.py#L163, I hard coded the labels I got from FreeSurfer into 46 labels:
 import re def process_label():     #process labeling information for FreeSurfer     seg_table = [0, 2, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 24, 26,                           28, 30, 31, 41, 42, 43, 44, 46, 47, 49, 50, 51, 52, 53, 54, 58, 60, 62,                           63, 72, 77, 80, 85, 251, 252, 253, 254, 255]     file1 = open('label_info.txt', 'r')     Lines = file1.readlines()     dict = {}     seg_i = 0     seg_look_up = []     for seg_label in seg_table:         for line in Lines:             line = re.sub(' +', ' ',line).split(' ')             try:                 int(line[0])             except:                 continue             if int(line[0]) == seg_label:                 seg_look_up.append([seg_i, int(line[0]), line[1]])                 dict[seg_i] = line[1]         seg_i += 1     return dict
 
Therefore, if the dataset you used was not preprocessed using FreeSurfer, then depending on how many labels you got, you should modify the code for dice calculation (e.g., num_classes, etc.) in https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/utils.py#L193:
 def dice_val_substruct(y_pred, y_true, std_idx):     with torch.no_grad():         y_pred = nn.functional.one_hot(y_pred, num_classes=46)         y_pred = torch.squeeze(y_pred, 1)         y_pred = y_pred.permute(0, 4, 1, 2, 3).contiguous()         y_true = nn.functional.one_hot(y_true, num_classes=46)         y_true = torch.squeeze(y_true, 1)         y_true = y_true.permute(0, 4, 1, 2, 3).contiguous()     y_pred = y_pred.detach().cpu().numpy()     y_true = y_true.detach().cpu().numpy()     line = 'p_{}'.format(std_idx)     for i in range(46):         pred_clus = y_pred[0, i, ...]         true_clus = y_true[0, i, ...]         intersection = pred_clus * true_clus         intersection = intersection.sum()         union = pred_clus.sum() + true_clus.sum()         dsc = (2.*intersection) / (union + 1e-5)         line = line+','+str(dsc)     return line
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.


从QQ邮箱发来的超大附件

6029a6ade1b6e55e0fde9dcc120ab28.png (88.7K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=3c62306630fecdcfbfea78364463011f515207565b01565349530153534e070850061d070054561d555354035a070a075506540762403306545009075402575555000603575656000206555f0600500156525104505b1d400a05305b&t=exs_ftn_download&code=db0fbc30




eb5b227ca688953afbf415fec19476b.png (82.2K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6166363059d3cd9de2ee7e604564014d0d5f07555a060a0614505253054907570d511b51055c034f0d520e565053525b09050006634733075b535402515350030f5e0e09565752045b00020156025601085f020755061d125701360d&t=exs_ftn_download&code=9f60cd3b




7ce027e6528afc99f5e9f2ac7bfabe5.png (86.2K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6e37613348c39ccaedbf29634064501a02050052515c51051b0004505549565602564c5105525118505405035f5201015303020b664762025552510151015400040f0055055d5b5303525855540501025451005103514c455850610e&t=exs_ftn_download&code=67a3fdb5

**Comment by junyuchen245** [comment]
@zhixiaoqiang-haha Just wanna double-check if you have also modified the label numbers here: https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/data/trans.py#L299-L311

No, I did not encounter this problem. Can you show me an example of the moving label map, fix label map, and warped label map?

Btw, it seems like the links in https://resource.loni.usc.edu/resources/atlases-downloads/ for downloading the LPBA40 dataset are broken. Do you happen to know where I can download this dataset?

**Comment by zhixiaoqiang-haha** [comment]
Hello&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;Regarding the part of the code about label in data/trans that you mentioned, I have also changed it before, but it did not solve this problem. I haven't found the specific reason for the low resolution of the images he generated. But this problem occurred after several training sessions. Below are the fixed label, moving label and warped label I provide you. I really trouble you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch] The process of making and loading datasets (#3)





 
@zhixiaoqiang-haha Just wanna double-check if you have also modified the label numbers here: https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/0041215d04919aed8bf6a67f80a7819e0de3b6f5/ViT-V-Net/data/trans.py#L299-L311
 
No, I did not encounter this problem. Can you show me an example of the moving label map, fix label map, and warped label map?
 
Btw, it seems like the links in https://resource.loni.usc.edu/resources/atlases-downloads/ for downloading the LPBA40 dataset are broken. Do you happen to know where I can download this dataset?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.


从QQ邮箱发来的超大附件

1fixed_seg (1).nii (37.50M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2664356599ce92c8baec7d351f30071a52500d5501040c544c010606011d0154530718070153501856020553580550575305560639223504070d4d005d6f465006441d54101e5b5c086408&t=exs_ftn_download&code=ad5e9055




1moving_seg (2).nii (37.50M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7a3936369198c6c9e9b17e661766531b0a5f0105000559051f090706074b5557070a1b5700550219050e530502575357500e0406317561055f56405f5f013e47575e161e034f4f5a5b50360b&t=exs_ftn_download&code=29661fa4




1warped_seg (1).nii (37.50M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2a373135c3cc91cab9bf79654532041806050607565307074f560251521f0205570f1c0d5053051a0602060052040051530505516321360615564345065669440750111d521b18590b5e3108&t=exs_ftn_download&code=b715c267

**Comment by junyuchen245** [comment]
Hi @zhixiaoqiang-haha, the low resolution may be caused by interpolation. 

I couldn't find out why the code did not work for you. I have tested this code on images from other modalities (e.g., whole-body CT), and it seemed to be working fine. I wanted to try this on the LPBA40 dataset, but I couldn't find where I can get the data. Sorry that I couldn't be more helpful.

**Comment by zhixiaoqiang-haha** [comment]
Thank you for your careful answer. I have really troubled you these few days. If I make progress in the follow-up, I will continue to keep in touch with you. Finally, I would like to say thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch] The process of making and loading datasets (#3)





 
Hi @zhixiaoqiang-haha, the low resolution may be caused by interpolation.
 
I couldn't find out why the code did not work for you. I have tested this code on images from other modalities (e.g., whole-body CT), and it seemed to be working fine. I wanted to try this on the LPBA40 dataset, but I couldn't find where I can get the data. Sorry that I couldn't be more helpful.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junyuchen245** [comment]
@zhixiaoqiang-haha You are most welcome! Please keep me posted.

**Comment by klxlingxiang** [comment]
Hello@junyuchen245,
     I am a novice, I would like to ask you how to convert your data set to PKL format, could you provide me with the code of conversion format, thank you very much.

**Comment by junyuchen245** [comment]
Hi @klxlingxiang,

The code for writing NumPy arrays to .pkl files is shown here https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/issues/3#issuecomment-886052972

Junyu
